### ISSUE TITLE
Запуск контейнера library-app без открытия GUI докера

### ISSUE THREAD

**Issue by iprst** [terratensor/library-app#2]
Докер GUI использует ускорение графики, которое конфликтует с HDR дисплеями в Windows 10. Эта проблема не будет иметь решения в будущем, поскольку HDR в Win10 в общем и целом брошен на произвол и в практическом смысле не поддерживается полностью. То есть одни приложения умеют работать при обходе расширенного потока на дисплей, другие не умеют. Например chrome не умеет использовать ускорение графики при отключенном в системе HDR, приходится отключать акселерацию браузера. С докером похожая проблема, однако ещё хуже, отключение ускорения не помогает — оно отключается, но интерфейс не просыпается: в системном режиме SDR окно чёрное без признаков жизни (так же себя ведёт хром со включенной акселерацией). Для работы с докером приходится вручную включать HDR в виндовс, что не удобно из-за плохой поддержки расширенной палитры Windows 10, при переключении системы в HDR интерфейс докера в окне становится доступен, но регулярно искажается какими-то системными процессами типа рисования теней окон, смены фона рабочего стола и тому подобного. Вот так выглядит докер после пары секунд простоя, картинка меняется только если поелозить курсором вокруг нужных полей, это нелепая дичь:

![image](https://github.com/user-attachments/assets/75733c9f-5900-4c1c-92b0-445edd6a6712)

Люди на форумах разных приложений по этому поводу возмущаются, полгода назад обещали новые драйвера для GPU, но всё это пока никуда не сдвинулось. Полагаю, мне нужно собрать какой-то батник аналогичный батнику start внутри репозитория, который будет запускать контейнер library-app со вложенными образами без необходимости открытия интерфейса докера. Нужно только, чтобы батник не собирал контейнер заново, а просто автоматически запускал уже существующий. Можно запускать докер без показа окна, или может быть есть вариант с установкой сервиса, без запуска GUI, в общем, пока далее решения вопроса я не знаю.

**Comment by audetv** [comment]
Кажется мене повезло, я такое ни разу не наблюдал у себя. 

Докер нельзя установить без GUI. Теперь даже на домашней ubuntu GUI по умолчанию. Без GUI только серверный вариант.
Но это ни значит, что нельзя докером пользоваться без GUI. я уже привык запускать все из консоли, пишу команды для запуска, для просмотра списка запущенных контейнеров и т.д. Добавляю их в make файл в wsl linux и запускаю сокращенные версии, типа `make up` Но не обязательно так делать, т.к. команды простые. и make больше нужен для запуска последовательности команд, когда надо сразу несколько выполнить. В большей степени работа в консоли была вызвана необходимостью администрировать приложения докер на сервере, там только консоль и доступна, с начала тяжело, потом привыкаешь. Но все равно иногда захожу в GUI в windows, чаще чтобы использовать встроенный терминал и не запускать его из консоли. Когда надо в самом контейнере выполнять команды. 

Замечал, что запуск и остановка контейнеров из консоли почти всегда происходит быстрее, чем нажимать кнопки запуска и остановки в GUI

В общем я для запуска использую docker-compose.yml и основные команды: `docker compose up -d` `docker compose down --remove-orphans`, `docker ps` `docker volume ls`  `docker image ls` `docker network ls` и т.д. 

Да, можно написать батник, чтобы запускать и останавливать докер. Я специально в текущем батнике сделал сборку подтягивание образа из репозитория, чтобы при каждом запуске происходило обновление.

Чтобы не собирал надо вызвать команду `docker compose up -d`,
чтобы подтянул изменения надо вызвать `docker compose up --pull -d` 
чтобы остановить без удаления контейнера, чтобы потом не собирал заново надо `docker compose down`
чтобы установить и удалить контейнер: `docker compose down --remove-orphans`
чтобы посмотреть список и ИД запущенных контейнеров надо `docker ps`
список всех контейнеров и остановленных и запущенных `docker ps -a`
и т.д. но это самый основной список команд для работы.

UPD^ Можно еще добавить в docker-compose.yml файл параметр restart: always и тогда докер сам будет запускать этот контейнер после запуска докера. Не надо будет даже батник дергать. Можно так сделать.

**Comment by iprst** [comment]
Кривое поведение зависит от драйверов и GPU, с этим фактически ничего поделать нельзя, MSFT давно сказали «нет не будем» и прекратили развитие десятки. В результате им теперь приходится прилагать усилия к поддержке в 11 версии старых процессоров, сокетов и тд, то есть значитально обогащать всю систему ошибками и конфликтами. 

Установка докера без GUI не требуется, пусть такой как есть. Нужно как раз лишь запуск всего необходимого, без обращения к GUI, из консоли командами. 

> добавить в docker-compose.yml файл параметр restart: always и тогда докер сам будет запускать этот контейнер после запуска докера. Не надо будет даже батник дергать

Вот, это оно. Я собирался так сделать через параметр рестарт, но не успел разобраться ещё, куда что там пишется в yml.

**Comment by audetv** [comment]
Пример файла с restart: always
```
services:
  app:
    image: ghcr.io/terratensor/library-app:main
    container_name: library-app
    restart: always
    volumes:
      - library-app:/app/data
    ports:
      - '8030:80'

  manticore:
    container_name: library-manticore
    image: manticoresearch/manticore
    restart: always
    environment:
      - EXTRA=1
    ports:
      - "127.0.0.1:9306:9306"
      - "127.0.0.1:9308:9308"
      - "127.0.0.1:9312:9312"

    cap_add:
      - IPC_LOCK
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - manticore:/var/lib/manticore
      - manticore:/var/log/manticore

volumes:
  library-app:
    name: library-app
  manticore:
    name: library_manticore
```

Но если по каким-то причинам контейнер не сможет запуститься, например придет глючное обновление от программиста. Докер будет бесконечно пытаться поднять контейнер. Другой момент, что в таком режиме обновление само не придет. Надо специально остановить контейнеры `docker compose down --remove-orphans` потом выполнить обновление и запуск `docker compose up --pull -d` После запуска проверить, что все прошло успешно `docker ps -a` посмотреть список. Можно добавить ограничения на кол-во попыток и прочее. Но обычно на локальных системах это не требовалось. я пользовался без таких настроек даже restart always не использовал, только на сервере в продакшен.

UPD про расширенные настройки рестарт вот тут вроде понятно изложено
https://dev.to/rohithv07/restart-policies-docker-compose-2c14
